lib/mygallery_web/router.ex
defmodule MygalleryWeb.Router do
  use MygalleryWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MygalleryWeb.Auth
  end

  pipeline :authorization do
    plug MygalleryWeb.Authorization
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MygalleryWeb do
    pipe_through [:browser, :authorization]
  end

  scope "/", MygalleryWeb do
    # Use the default browser stack
    pipe_through :browser

    get "/", PageController, :index
    resources "/artist", ArtistController
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", MygalleryWeb do
  #   pipe_through :api
  # end
end

lib/mygallery_web/views/layout_view.ex
defmodule MygalleryWeb.LayoutView do
  use MygalleryWeb, :view
  alias Mygallery.Accounts

  def role_id(name) do
    Accounts.get_role(name)
  end
end

lib/mygallery_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no"/>
    <title> Gallery App</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <style type="text/css">
      .btn-sm{
        margin-left: 700px;
      }

    </style>
  </head>
  <body>
    <header>


        <nav class="navbar navbar-expand-lg bg-dark navbar-dark justify-content-center">
          <a class="navbar-brand" href="/"><img src="/images/gallery.png" alt="Logo" style="width:50px;"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse lg-right" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link active  small" href="/">Home <span class="sr-only">(current)</span></a>
              <%= if @current_user do %>
              <%= if @current_user.role_id == role_id("admin") do %>
              <a class="nav-item nav-link small" href="/artist">Artists</a>
              <% end %>
              <% end %>
              <a id="reg" class="nav-item nav-link small" href="/artist/new">Register</a>
              <%= if @current_user do %>
                <%= @current_user.first_name %>
                <%= link "Log Out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete", class: "btn btn-info" %>
              <% else %>
                <%= link "Log In", to: Routes.session_path(@conn, :new), class: "btn btn-outline-success btn-sm font-weight-bold" %>
              <% end %>
            </div>
          </div>
        </nav>

    </header>
    <main role="main" class="container">
    <%= unless is_nil(get_flash(@conn, :info)) do %>
      <div class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></div>
    <% end %>
    <%= unless is_nil(get_flash(@conn, :error)) do %>
      <div class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></div>
    <% end %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>