lib/mygallery_web/router.ex
defmodule MygalleryWeb.Router do
  use MygalleryWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MygalleryWeb.Auth
  end

  pipeline :authorization do
    plug MygalleryWeb.Authorization
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MygalleryWeb do
    pipe_through [:browser, :authorization]
  end

  scope "/", MygalleryWeb do
    # Use the default browser stack
    pipe_through :browser

    get "/", PageController, :index
    resources "/artist", ArtistController
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", MygalleryWeb do
  #   pipe_through :api
  # end
end

lib/mygallery/accounts/user.ex
defmodule Mygallery.Accounts.User do
  @moduledoc """
  user schema
  """
  use Ecto.Schema
  import Ecto.Changeset
  alias Mygallery.Accounts.{Credential, Role}

  schema "users" do
    field(:first_name, :string)
    field(:last_name, :string)
    field(:phone_number, :string)
    field(:admin, :boolean)
    has_one(:credential, Credential)
    belongs_to(:role, Role)

    timestamps()
  end

  def changeset(user, attrs \\ %{}) do
    user
    |> cast(attrs, [
      :first_name,
      :last_name,
      :phone_number,
      :admin,
      :role_id
    ])
    |> validate_required([:first_name, :last_name, :phone_number, :admin, :role_id])
  end

  def user_registration(user, params) do
    user
    |> changeset(params)
    |> cast_assoc(:credential, with: &Credential.changeset/2, required: true)
  end
end

lib/mygallery_web/controllers/user_controller.ex
defmodule MygalleryWeb.UserController do
  use MygalleryWeb, :controller
  alias Mygallery.Accounts
  alias Mygallery.Accounts.User

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => params}) do
    case Accounts.create_user(params) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Registration Successful")
        |> redirect(to: "/")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Unsuccessful try again")
        |> render("new.html", changeset: changeset)
    end
  end
end

lib/mygallery_web/views/user_view.ex
defmodule MygalleryWeb.UserView do
  use MygalleryWeb, :view
end

lib/mygallery_web/templates/user/new.html.eex
<h1>Register</h1>
<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>

<div>
<%= label f, :first_name, "First Name"%>
<%= text_input f, :first_name, placeholder: "First Name"%>
 <%= error_tag f, :first_name %>
</div>
<div>
<%= label f, :last_name, "Last Name"%>
<%= text_input f, :last_name, placeholder: "Last Name"%>
 <%= error_tag f, :last_name %>
</div>

<div>
<%= label f, :phone_number, "Phonenumber"%>
<%= text_input f, :phone_number, placeholder: "+254789874652" %>
 <%= error_tag f, :phone_number %>
</div>

<div>
<%= label f, :email, "Email Adress"%>
<%= email_input f, :email, placeholder: "jane@example.com" %>
 <%= error_tag f, :email %>
</div>
<div>
<%= label f, :password, "Password"%>
<%= password_input f, :password, placeholder: "Password" %>
 <%= error_tag f, :password %>
</div>
<div>
<%= label f, :password_confirmation, "Confirm Password"%>
<%= password_input f, :password_confirmation, placeholder: "Confirm Password" %>
 <%= error_tag f, :password_confirmation %>
</div>

<%= submit "Register" %>
<% end %>

  		
  		
  		